serviceMaps:
  serviceName: adv-registration
  mappings:
    - version: 1.0
      description: Manage advocate registration persistence
      fromTopic: save-adv-application
      isTransaction: true
      queryMaps:
        - query: insert into eg_adv_register (id, tenantId, applicationId, state, district, city, firstName, middleName, lastName, phone, createdBy, lastModifiedBy, createdTime, lastModifiedTime) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?);
          basePath: $.application
          jsonMaps:
            - jsonPath: $.application.id

            - jsonPath: $.application.tenantId

            - jsonPath: $.application.applicationId

            - jsonPath: $.application.state

            - jsonPath: $.application.district

            - jsonPath: $.application.city

            - jsonPath: $.application.firstName

            - jsonPath: $.application.middleName

            - jsonPath: $.application.lastName

            - jsonPath: $.application.phone

            - jsonPath: $.application.auditDetails.createdBy

            - jsonPath: $.application.auditDetails.lastModifiedBy

            - jsonPath: $.application.auditDetails.createdTime

            - jsonPath: $.application.auditDetails.lastModifiedTime

        - query: insert into eg_adv_bar_detail (id, registrationId, barRegistrationNum, barRegistrationDocUrl, designation) values (?,?,?,?,?);
          basePath: $.application.advocateDetails
          jsonMaps:
            - jsonPath: $.application.advocateDetails.id

            - jsonPath: $.application.advocateDetails.registrationId

            - jsonPath: $.application.advocateDetails.barRegistrationNum

            - jsonPath: $.application.advocateDetails.barRegistrationDocUrl

            - jsonPath: $.application.advocateDetails.designation


    - version: 1.0
      description: manage advocate registration updates
      fromTopic: update-adv-application
      isTransaction: true
      queryMaps:
        - query: update eg_adv_bar_detail set barRegistrationNum = ?, barRegistrationDocUrl = ?, designation = ? where id = ?;
          basePath: $.advocateDetails
          jsonMaps:
            - jsonPath: $.advocateDetails.barRegistrationNum

            - jsonPath: $.advocateDetails.barRegistrationDocUrl

            - jsonPath: $.advocateDetails.designation